version: '3.7'

services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: devtoday
      POSTGRES_PASSWORD: devtoday1234
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /code/manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: